<<<<<<< HEAD
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider";
import { FloatingShapes } from "@/components/floating-shapes";
import { Toaster } from "sonner";
=======
import FloatingShapes from "@/components/floating-shapes";
import { Inter} from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
>>>>>>> a953cef4ceed79b2e6dcec49d6d9999c1d5af249

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "Pixel",
  description: "AI Image Editor",
>>>>>>> a953cef4ceed79b2e6dcec49d6d9999c1d5af249
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
        <ThemeProvider
<<<<<<< HEAD
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >

          <Header />

          <main className="bg-slate-900 min-h-screen text-white overflow-x-hidden">
            <FloatingShapes />
            <Toaster richColors />

            {children}
          </main>
=======
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* {<header/>} */}
            <main className="bg-slate-900 min-h-[2000px] text-white overflow-x-hidden">
            <FloatingShapes />
            <Toaster richColors/>
            {children}
            </main>

>>>>>>> a953cef4ceed79b2e6dcec49d6d9999c1d5af249
        </ThemeProvider>
      </body>
    </html>
  );
}
